name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ACCESS_TOKEN: ${{ secrets.PAT }}
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run project
      run: python main.py
      
    - name: Write to file
      run: date +%s > my_file_test.txt

    - name: test Commit changes
      run: |
        git config --global user.email "geissoncr@gmail.com"
        git config --global user.name "geissoncr"
        git add .
        git commit -m "Test de gravação de arquivos"
        git push https://$ACCESS_TOKEN@github.com/Geissoncr/quantos-seguidores.git
