
name: Daily Excution
run-name: ${{ github.actor }} was made dis action
on:
  schedule:
    - cron: '59 23 * * *'
    # Adicione esta linha para liberar o botão de execução manual
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
    
    - name: Run project
      run: python main.py

    - name: Commit changes
      run: |
        git config --global user.email "geissoncr@gmail.com"
        git config --global user.name "geissoncr"
        git add .
        git add .
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Update seguidores file [skip ci]"
          git push
        else
          echo "Nenhuma alteração detectada no arquivo de seguidores."
        fi
        
